### ISSUE TITLE
column hiding problem in cdk/mat-table-exporter for two digit column indexes

### ISSUE THREAD

**Issue by HalitTalha** [HalitTalha/mat-table-extensions#1]
Column hiding through the directive is problematic when hiding the columns that have two digit index numbers.

**Comment by HalitTalha** [comment]
Turns out to be no bug.

**Comment by teamsmiley** [comment]
it just happening to me can you check?

**Comment by HalitTalha** [comment]
Could you share how you bind the array to hiddenColumns input?

**Comment by teamsmiley** [comment]
[0,3,5,7] => works
[0,3,5,7,10] => not work remove 1
[0,3,5,7,11]  ==> remove 1 
[0,3,5,7,12]  => remove 1

**Comment by HalitTalha** [comment]
Updated stackblitz.

**Comment by iammurtaza53** [comment]
> Updated stackblitz.

PLease share the link

**Comment by HalitTalha** [comment]
> 
> 
> > Updated stackblitz.
> 
> PLease share the link

Stack blitz demos are outdated. I'll update them all.
But you can check the first exporter example here: https://halittalha.github.io/ng-material-extensions/
