### ISSUE TITLE
Ability to add custom compare function to each column

### ISSUE THREAD

**Issue by csegedicsaba** [HalitTalha/mat-table-extensions#13]
It would be great to add custom filter function for some columns. For example the array type columns could be handled.

**Comment by HalitTalha** [comment]
Thanks for the suggestion. I may not find the required time to look at it for a while. I wouldn't say no to any contribution :)

**Comment by HalitTalha** [comment]
Custom filtering option is provided in the new release. You can see in the docs api section.
