### ISSUE TITLE
Last page data is missing in the export for large datasets

### ISSUE THREAD

**Issue by hemanthvhs** [HalitTalha/mat-table-extensions#14]
While exporting to excel , the table data of the last page ( pagination ) is not exported.
This is happening , if the data rows are larger . Found for the data > 4000 items

**Comment by HalitTalha** [comment]
Thanks for reporting. What was the page row count for each page in your case? I want to reproduce the case.

**Comment by hemanthvhs** [comment]
Per page we have 10 rows, Total rows  4356

**Comment by HalitTalha** [comment]
@hemanthvhs 
I couldn't reproduce your case. Here is a stackblitz demonstrating a large dataset export without any issue. The last page is successfully included in the export file. https://stackblitz.com/edit/mte-demo-ibsvjj 
Could you create a stacblitz of your case? Or if you can share your table template and last page of your dataset, it could be helpful.

**Comment by hemanthvhs** [comment]
I have been seriously working on this for the past 3 days trying to figure out the issue. But I'm not able to resolve the issue. I saw your stackblitz example & it's working fine. In my case last page data is missing. Any idea what could be the issue. Also, Instead of calling exporter.exportTable('xlsx') in html ,  Can I call this in .ts ?

**Comment by HalitTalha** [comment]
Yes you can call it in your .ts
You need to reference the directive for it;
`  @ViewChild(MatTableExporterDirective, {static: true}) exporter;`

However you can also show/hide a spinner by using exportStarted and exportCompleted events.
Something like this:
 `<mat-table matTableExporter [dataSource]="dataSource" (exportStarted)="showSpinner()" (exportCompleted)="hideSpinner()" ...`

**Comment by HalitTalha** [comment]
Closed because of inactivity.
