### ISSUE TITLE
Receive "Can't bind to 'matTableFilter' since it isn't a known property of 'table'" after upgrading to version 1.2.1

### ISSUE THREAD

**Issue by jacknkandy** [HalitTalha/mat-table-extensions#19]
I have just tried upgrading the `mat-table-filter` package to version 1.2.1 and am receiving the following error: "Can't bind to 'matTableFilter' since it isn't a known property of 'table'".

I am running Angular Materials 8.2.3.

Cheers

**Comment by HalitTalha** [comment]
Thanks for clarifying. This is expected behavior. matTableFilter input is removed in b76b448. That was a breaking change.

**Comment by jacknkandy** [comment]
Thanks for clarifying @HalitTalha
