### ISSUE TITLE
paginator error

### ISSUE THREAD

**Issue by airasyaqub** [HalitTalha/mat-table-extensions#2]
Even I am not using the paginator in my table but still, it's throwing this error. Can you please give urgent support on it
![errorrr](https://user-images.githubusercontent.com/30695220/57131812-06adb180-6db7-11e9-89f4-998857dd2237.PNG)

**Comment by HalitTalha** [comment]
Thanks for reporting. Im marking as a bug and fix it as soon as possible. The reason of the error is mat-table-exporter tries to find angular material pagination buttons to disable during export even if you don't have pagination in your table.
However it should be exporting the table anyway, so this should'nt be a blocker for export.

**Comment by airasyaqub** [comment]
yeah, it doesn't block the export but breaks the app. what could be the workaround for this for the time being? Or how long the bugfix will come.

**Comment by HalitTalha** [comment]
Workaround could be putting a paginator for the time being.
`<mat-paginator [hidePageSize]="true" [pageSize]="10" showFirstLastButtons></mat-paginator>`

I'm planning to release the fix along with one other item and some more features in mind. The release hopefully will be within next 12 hours.

When I tested without a paginator, I couldn't see any side effects other than the error log in the console actually. In what other sense does it affect your application?

**Comment by airasyaqub** [comment]
great :) thanks for the support. I'll put the screenshot in a bit.

**Comment by airasyaqub** [comment]
it just disables my export button. 

`<button #exportButton mat-stroked-button>
       <mat-icon aria-label="Export">arrow_downward</mat-icon>
	Export
</button>`

`<mat-table [dataSource]="reportByMonthDataSource" #mytable ngxMatTableExporter [cdkTable]="mytable" [exporterButton]="exportButton" sheetName="someSheetName" fileName="someFileName">
// table content
</mat-table>`

![disbale](https://user-images.githubusercontent.com/30695220/57140756-ef2ff200-6dd1-11e9-9de3-cf40d0a2c1b7.PNG)

**Comment by airasyaqub** [comment]
I am having the same problem with paginator too. 
![againerror](https://user-images.githubusercontent.com/30695220/57141634-18518200-6dd4-11e9-8816-62ac134b5fa2.PNG)

**Comment by HalitTalha** [comment]
Fixed with the latest release.

**Comment by bellamira** [comment]
I am using a paginator and I am getting a similar error. Do I need to declare something in the component code?

```
ERROR TypeError: Cannot read property 'paginator' of undefined
    at MatTableExporterDirective.push../node_modules/mat-table-exporter/fesm5/mat-table-exporter.js.MatTableExporterDirective.getPaginator (mat-table-exporter.js:130)
    at MatTableExporterDirective.push../node_modules/mat-table-exporter/fesm5/mat-table-exporter.js.MatTableExporterDirective.ngAfterViewInit (mat-table-exporter.js:33)
    at callProviderLifecycles (core.js:22416)
    at callElementProvidersLifecycles (core.js:22390)
    at callLifecycleHooksChildrenFirst (core.js:22380)
    at checkAndUpdateView (core.js:23316)
    at callViewAction (core.js:23548)
    at execComponentViewsAction (core.js:23490)
    at checkAndUpdateView (core.js:23313)
    at callViewAction (core.js:23548)
```

Here is my table:
```
<table
    mat-table
    [dataSource]="dataSource"
    multiTemplateDataRows
    matSort
    #logTable
    ngxMatTableExporter
    [cdkTable]="logTable"
    [exporterButton]="exportButton"
    [fileName]="fileName"
    [sheetName]="fileName"
    hiddenColumns="[4]"
    (exportStarted)="exportStarted()"
    (exportCompleted)="exportCompleted()">
    
    ...

</table>
<mat-paginator pageSize="10" [pageSizeOptions]="[5, 10, 25, 100]"></mat-paginator>
```

**Comment by HalitTalha** [comment]
Yes, I should have mentioned that in the docs.
You need to set the paginator property of your datasource, if you will use it with pagination.

**In your ts file:**
```
@ViewChild(MatPaginator) paginator: MatPaginator;
  ngOnInit(): void {
    this.dataSource.paginator = this.paginator;
  }
```

**Comment by bellamira** [comment]
I believe this is correct.

<img width="467" alt="Capture" src="https://user-images.githubusercontent.com/19840320/63596693-cf435a80-c589-11e9-9263-a27c40d389d0.PNG">
