### ISSUE TITLE
Using custom exporter and other defaults like xlsx is causing issues

### ISSUE THREAD

**Issue by arindamdawn** [HalitTalha/mat-table-extensions#20]
I loved this extension. However I have a requirement where I need to export the mat table as xlsx as well as PDF. For pdf I am using the custom export feature of this extension and referred to this link mentioned in the docs -> https://stackblitz.com/edit/mte-cex-demo

I have just added another button like this 
<button mat-raised-button (click)="exportDirective.exportTable('other')">Custom Export</button>
<button mat-raised-button (click)="exportDirective.exportTable('xlsx')">Excel Export</button>

On clicking the custom export button, the functionality works fine, however, once I click on the xlsx button and then the custom export button, it starts exporting the xlsx file instead of the custom log statement. 

Can you help me resolve this issue?

**Comment by HalitTalha** [comment]
Thanks for reporting the issue. It is going to be fixed in the next patch release very soon.

**Comment by HalitTalha** [comment]
Fixed in new release (1.2.5)
