### ISSUE TITLE
for which versions this mat table exporter will work? Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by sudharsan203** [HalitTalha/mat-table-extensions#21]
I am using angular 6.0.2, I am getting this error

Uncaught TypeError: Object(...) is not a function
    at cdk-table-exporter.js:726
    at Object../node_modules/cdk-table-exporter/fesm5/cdk-table-exporter.js (cdk-table-exporter.js:728)
    at __webpack_require__ (bootstrap:81)
    at Object../node_modules/mat-table-exporter/fesm5/mat-table-exporter.js (loglevel.js:250)
    at __webpack_require__ (bootstrap:81)
    at Object../src/app/app.module.ts (app.component.ts:10)
    at __webpack_require__ (bootstrap:81)
    at Object../src/main.ts (environment.ts:14)
    at __webpack_require__ (bootstrap:81)
    at Object.0 (main.ts:14)

**Comment by paperez** [comment]
I have the same issue.

If I'm not wrong, this is happening because the lib has been packaged using Angular 8 Ivy, which breaks backward compatibility.

Check if you are receiving several of these warnings as well
`./node_modules/cdk-table-exporter/fesm5/cdk-table-exporter.js 1023:169-177
"export 'ɵɵinject' was not found in '@angular/core'`

Your @angular/core version is probably v6.x.x and it is expected to be v8.x.x

- v1.2.1 **works**
- v1.2.2 **doesn't work**

**Comment by HalitTalha** [comment]
@sudharsan203 As a workaround you can clone and build the library locally and use that package. Actually In cdk-table-exporter peer-dependencies state it expects at least angular 7 so we are manifesting to support only after 7 however as @paperez said it was working before it is packaged with CLI 8. For now I will fix it with the next patch release by building accordingly however later on we may need different tags for specific Angular versions.

Thank you both :)

cdk-table-exporter's package.json (mat-table-exporter depends on cdk-table-exporter)
```
 "peerDependencies": {
    "@angular/common": "^7.0.0 || ^8.0.0",
    "@angular/core": "^7.0.0 || ^8.0.0",
    "@angular/cdk": "^7.0.0 || ^8.0.0"
  },
```

**Comment by MaryCooperGD** [comment]
Hi, I'm having the same issue and I don't know what are the correct versions to solve this. 
In particular, I have these warnings:

```
WARNING in ./node_modules/cdk-table-exporter/fesm5/cdk-table-exporter.js 726:61-79
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/cdk-table-exporter/fesm5/cdk-table-exporter.js 839:60-78
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/cdk-table-exporter/fesm5/cdk-table-exporter.js 903:60-78
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/cdk-table-exporter/fesm5/cdk-table-exporter.js 936:61-79
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/cdk-table-exporter/fesm5/cdk-table-exporter.js 978:60-78
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/cdk-table-exporter/fesm5/cdk-table-exporter.js 1023:63-81
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/cdk-table-exporter/fesm5/cdk-table-exporter.js 1192:62-80
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/cdk-table-exporter/fesm5/cdk-table-exporter.js 1023:169-177
"export 'ɵɵinject' was not found in '@angular/core'
```


The versions in my package.json file are:

   ```
"@angular/animations": "7.2.15",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "^7.2.15",
    "@angular/compiler": "^7.2.15",
    "@angular/core": "^7.2.15",
    "@angular/forms": "^7.2.15",
    "@angular/http": "^7.2.15",
    "@angular/material": "^7.3.7",
    "@angular/material-moment-adapter": "^7.3.7",
    "@angular/platform-browser": "^7.2.15",
    "@angular/platform-browser-dynamic": "^7.2.15",
    "@angular/platform-server": "^7.2.15",
    "cdk-table-exporter": "1.2.1",
    "mat-table-exporter": "1.2.1",
```

**Comment by HalitTalha** [comment]
Thanks for reporting.

The only workaround is updating your project to Angular 8 for now.
I will release a separate version to support the versions prior to 8 soon.
Actually the next patch release along with this is on the way for about 3 weeks, it is almost ready but I just couldn't find enough time to make the final move. :) Hopefully it will be released this week anyway.

**Comment by MaryCooperGD** [comment]
> Thanks for reporting.
> 
> The only workaround is updating your project to Angular 8 for now.
> I will release a separate version to support the versions prior to 8 soon.
> Actually the next patch release along with this is on the way for about 3 weeks, it is almost ready but I just couldn't find enough time to make the final move. :) Hopefully it will be released this week anyway.

Hi, thank you.
Unfortunately I have to use Angular 7 (project directives) so I'm looking for another solution

**Comment by HalitTalha** [comment]
Actually there is one more way but it is somewhat effortfull. You can clone the library and change the Angular version for mat-table-extensions package.json then build the libraries to use your own build for Angular 7

**Comment by dimespi** [comment]
@HalitTalha Do you have some news about the release that will fix that? I'm also using angular 7

**Comment by HalitTalha** [comment]
@dimespi I'll try to make it today. Seems like too many people still have to use old versions of Angular.

**Comment by HalitTalha** [comment]
I'm planning to provide support since Angular 5. There will be two different branches one for prior-8, and one for 8. Once a stable release for Angular 9 is out we will probably need a different release for it too. I have completed most of the work, you need to stand just a little longer, I think I will be able to make it this weekend :)

**Comment by drc-kmonagle** [comment]
@HalitTalha Thanks for your work on this great package! Any updates on a fix for this particular issue?

**Comment by HalitTalha** [comment]
I know I've been off the schedule for a long long time. :)
But it's on the way, about to come out tonight or tomorrow. I'm also adding a showcase page and I'll probably rename the repo as material-extensions. Because there will be a few more usefull things that want to share soon and they are not about tables.

**Comment by HalitTalha** [comment]
Finally angular 6.3 -7 compatible version of exporter is relased. 

`npm i mat-table-exporter@1.2.3-ng67 `

This release is done from newly created ng6-7 branch. This branch has the latest fixes and enhancements that we have not applied for master yet.

Master branch will be for latest Angular version.

**Comment by HalitTalha** [comment]
The new release from master branch is compatible in between ^6.3.0 - ^8.0.0
