### ISSUE TITLE
excel with more than one exported table 

### ISSUE THREAD

**Issue by rcodinat** [HalitTalha/mat-table-extensions#22]
Hi,

Is there a possibility to export several tables at the same time and having them in the same excel sheet?

If so, how?
If not, do you plan on having it in the near future?

I think it would be great to have this feature since people need to export several tables from the same page at the same time pretty often, not just one table.

Many thanks for your reply.

Best,
Rafael

**Comment by HalitTalha** [comment]
Thank you for the feedback. Currently it is not possible however multiple export is in consideration and there is a feature request about it already. Do you mean exporting multiple tables in the same excel file or same excel sheet?

**Comment by rcodinat** [comment]
Hi, thank you for replying.
I mean exporting multiple tables in the same sheet of an excel file.
It would be great:
- to be able to indicate, while exporting, how many tables the user wants
to put side by side.
- to be able to add some css/formatting to the tables.

Do you guys have an idea of an approx. Date /month when a "beta" version of
this feature could be available?

Best,
R.


Le mar. 19 nov. 2019 à 20:07, Halit Talha TÜRE <notifications@github.com> a
écrit :

**Comment by HalitTalha** [comment]
Thanks for letting us know your requirement however having multiple tables in one sheet is actually a common misuse of excel. You can follow this issue #18 for multiple table exporting cases.
