### ISSUE TITLE
Not Export Some columns like action columns where i have a button edit,add, etc...

### ISSUE THREAD

**Issue by CedLP** [HalitTalha/mat-table-extensions#24]
Hello, can i have a possibility to export a datatable without a some colomuns like actions colums? 
If yes how can i do this please? 

Thanks

**Comment by HalitTalha** [comment]
You can hide the columns you want with their column index.

<mat-table></mat-table>
You can also check the stackblitz demo:
https://stackblitz.com/edit/mte-demo
