### ISSUE TITLE
when i exported my data table as text .it adds 2 korean letters.which when i translated says"can i take u home tonight".i was shicked

### ISSUE THREAD

**Issue by harishSA05** [HalitTalha/mat-table-extensions#28]
[mat-table-exporter.txt](https://github.com/HalitTalha/mat-table-extensions/files/3983439/mat-table-exporter.txt)

**Comment by HalitTalha** [comment]
:D Thanks for reporting however this is a duplicate issue record. You can check for #26 details. We will take care of this soon.
