### ISSUE TITLE
Is there a way to manually call the export function?

### ISSUE THREAD

**Issue by bellamira** [HalitTalha/mat-table-extensions#3]
Is there a way to manually call the export function on the button, so you can do some stuff before the export starts? Something like this:

```
<button mat-button (click)="myExportFunction()">EXPORT</button>

myExportFunction() {
    doSomething();
    matTableExporterFunction();
}
```

Great extension!

**Comment by HalitTalha** [comment]
Many thanks for the feedback.
Yes, actually the exportStarted event is emitted just before the real exporting happens. You can listen to that event.

component template
  `<mat-table .........  (exportStarted)="onExportStarted()">`

component.ts

>   onExportStarted() {
>     alert('export started');
>   }

**Comment by bellamira** [comment]
Oh excellent! I did not read the documentation thoroughly enough. Thank you!
