### ISSUE TITLE
HiddenColumns property problem

### ISSUE THREAD

**Issue by zebt** [HalitTalha/mat-table-extensions#37]
Hey,

I have a small problem with extension.

When, I set for instance `hiddenColumns="13"` it will actually hide columns with index 1 and 3, not 13.

**Comment by HalitTalha** [comment]
`hiddenColumns `is an `Array`. Please make sure `hiddenColumns `is surrounded by [ ]
like so: 
`[hiddenColumns] = "[3,5,11]"`

Duplicate of  #1
