### ISSUE TITLE
ng build --prod throwing ERROR in Directive CdkTableExporter mat-table-exporter/node_modules/cdk-table-exporter/cdk-table-exporter.d.ts has no selector, please add it!

### ISSUE THREAD

**Issue by selwyntheo** [HalitTalha/mat-table-extensions#48]
After adding the mat-table-exporter and cdk-table-exporter in the ngModules, I am getting an error 

mat-table-exporter/node_modules/cdk-table-exporter/cdk-table-exporter.d.ts has no selector, please add it!

**Comment by selwyntheo** [comment]
This got rectified after I used the same version for mat-table-exporter and cdk-table-exporter.
We should highlight the dependency of the version between the two modules.

**Comment by HalitTalha** [comment]
If you are not using cdk-table-exporter class specifically you do not have to npm install it and import it's module by the way.
