### ISSUE TITLE
MatTableExporterModule does not work with Angular 8

### ISSUE THREAD

**Issue by constanzasanmartino** [HalitTalha/mat-table-extensions#6]
MatTableExporterModule does not work with Angular 8, 
Is there any alternative?

**Comment by HalitTalha** [comment]
Could you share whats the case exactly? Conaole output, error log etc

**Comment by constanzasanmartino** [comment]
When I run: npm install --save mat-table-exporter..
![captura](https://user-images.githubusercontent.com/31261472/64361813-af795100-cfe3-11e9-9540-855ff142c945.PNG)

**Comment by HalitTalha** [comment]
These are warnings indicating that your installed versions may not be compatible with mat-table-exporter. It should work anyway. I'll try to update the peer dependencies soon, apperantly I missed it.

**Comment by HalitTalha** [comment]
Peer dependency versions is changed accordingly.
