### ISSUE TITLE
Format Excel File Prior To Export

### ISSUE THREAD

**Issue by chrisbirie** [HalitTalha/mat-table-extensions#7]
Is there a way to format the excel file prior to export?

**Comment by HalitTalha** [comment]
Formatting support is on the way. I've actually completed most of the coding for number formatting support. What's your exact requirement or advice for it? I'd appriciate any help.

**Comment by chrisbirie** [comment]
The biggest thing would be to have the column width changed in Excel, even if it is auto width. Other things like header format and color would be a start. I am pretty sure the xlsx plugin is able to do that somehow, I will do some research for you though!

**Comment by HalitTalha** [comment]
Feel free to fork and implement if you have time, contributions are wellcome :)

**Comment by klaydze** [comment]
Just checking in. 
I'm also waiting for this feature specially the option to resize the column and change the font weight. 

Cheers!

**Comment by klaydze** [comment]
> The biggest thing would be to have the column width changed in Excel, even if it is auto width. Other things like header format and color would be a start. I am pretty sure the xlsx plugin is able to do that somehow, I will do some research for you though!

Do you have luck finding a plugin? Can you share how do you handle this? Thanks!

**Comment by HalitTalha** [comment]
@klaydze This is still in progress. There will be a patch release soon. I was actually planning to publish 2 weeks ago but other priorities kicked in. I will try to include at least the column size and font weight options. 
Thanks for informing.

**Comment by klaydze** [comment]
> @klaydze This is still in progress. There will be a patch release soon. I was actually planning to publish 2 weeks ago but other priorities kicked in. I will try to include at least the column size and font weight options.
> Thanks for informing.

Very much appreciated if ever you included this features in your next patch soon! We'll waiting for this feature to be honest. 🙂

Thank you!

**Comment by HalitTalha** [comment]
Feature to set column width in excel files is availabe in the new release (1.2.5)
However due to some bug in sheetjs it is only working for xlsx format.
