### ISSUE TITLE
Cannot generate file: ERROR TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by falcon-europe** [HalitTalha/mat-table-extensions#8]
I have following issue when I want to generate file using Mat Table Exporter

ERROR TypeError: Cannot read property 'length' of undefined
    at DataExtractorService.convertRow (cdk-table-exporter.js?c021:971)

`function (hiddenColumns, row) {
        /** @type {?} */
        var result = new Array();
        /** @type {?} */
        var cells = row.children;
        for (var i = 0; i < cells.length; i++) {
            if (!this.shouldHide(hiddenColumns, i)) {
                /** @type {?} */
                var element = cells.item(i).innerText;
                result.push(element);
            }
        }
        return result;
    };`

Object row has following properties:

`childNodes: NodeList []
data: ""
firstChild: null
isConnected: true
lastChild: null
length: 0
nextElementSibling: div.mat-header-row.header-group-row.ng-star-inserted
nextSibling: div.mat-header-row.header-group-row.ng-star-inserted
nodeName: "#comment"
nodeType: 8
nodeValue: ""
ownerDocument: document
parentElement: mat-table.mat-table.ng-star-inserted
parentNode: mat-table.mat-table.ng-star-inserted
previousElementSibling: null
previousSibling: comment
textContent: ""
__proto__: Comment`

**Comment by HalitTalha** [comment]
Could you share your angular material, angular and mat-table-exporter version?

**Comment by falcon-europe** [comment]
"@angular/material": "^7.3.5" ("7.3.7")
"mat-table-exporter": "^1.2.1" ("1.2.1")

mat-table has following structure:

`<mat-table
        [dataSource]="dataSource.positions"
        *ngIf="someCondition">

    <ng-container *matHeaderRowDef="displayedColumns">
        <div>
            <div>
                Header 1
            </div>
            <div>
                Header 2
            </div>
            <div>
                Header 3
            </div>
        </div>
        <mat-header-row></mat-header-row>
    </ng-container>

    <mat-row
            *matRowDef="let row; columns: displayedColumns; let i = index"
            (click)="onRowClick(i)">
    </mat-row>

    <ng-container matColumnDef="id">
        <mat-header-cell *matHeaderCellDef></mat-header-cell>
        <mat-cell *matCellDef="let element">
            {{ element.someValue }}
        </mat-cell>
    </ng-container>

    <ng-container matColumnDef="some2">
        <mat-header-cell *matHeaderCellDef></mat-header-cell>
        <mat-cell *matCellDef="let element">
            {{ element.someValue }}
        </mat-cell>
    </ng-container>

    <ng-container matColumnDef="some3">
        <mat-header-cell *matHeaderCellDef></mat-header-cell>
        <mat-cell *matCellDef="let element">
            {{ element.someValue }}
        </mat-cell>
    </ng-container>

    <ng-container matColumnDef="some4">
        <mat-header-cell *matHeaderCellDef></mat-header-cell>
        <mat-cell *matCellDef="let element">
            {{ element.someValue }}
        </mat-cell>
    </ng-container>
    
    ...

</mat-table>`

**Comment by HalitTalha** [comment]
Your header row definition is incomplete. You are supposed to define your header row like this:
    `<mat-header-row *matHeaderRowDef="displayedColumns"></mat-header-row>`
Stackblitz demo: https://stackblitz.com/edit/mte-demo

Example: 
```
  <mat-table matTableExporter [dataSource]="dataSource" #exporter="matTableExporter" hiddenColumns="[0]">

    <ng-container matColumnDef="position">
      <mat-header-cell *matHeaderCellDef> No. </mat-header-cell>
      <mat-cell *matCellDef="let element"> {{element.position}} </mat-cell>
    </ng-container>

    <ng-container matColumnDef="name">
      <mat-header-cell *matHeaderCellDef> Name </mat-header-cell>
      <mat-cell *matCellDef="let element"> {{element.name}} </mat-cell>
    </ng-container>

    <ng-container matColumnDef="surname">
      <mat-header-cell *matHeaderCellDef> Surname </mat-header-cell>
      <mat-cell *matCellDef="let element"> {{element.surname}} </mat-cell>
    </ng-container>

    <ng-container matColumnDef="birth">
      <mat-header-cell *matHeaderCellDef> Birth </mat-header-cell>
      <mat-cell *matCellDef="let element"> {{element.birth}} </mat-cell>
    </ng-container>

    <mat-header-row *matHeaderRowDef="displayedColumns"></mat-header-row>
    <mat-row *matRowDef="let row; columns: displayedColumns;"></mat-row>
  </mat-table>
```
